assets:
  settings.xml: baudoliver7/home#assets/settings.xml
  public.key: baudoliver7/home#assets/public.key
  private.key: baudoliver7/home#assets/private.key
architect:
  - baudoliver7
install: |
  sudo apt install openjdk-8-jdk -y
  sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  sudo gem install pdd
  sudo gem install xcop
  pdd --file=/dev/null
merge:
  fast-forward: only
  rebase: true
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  script: |-    
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    gpg --import /home/r/public.key
    gpg --allow-secret-key-import --import --batch --pinentry-mode=loopback /home/r/private.key 
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Psonatype -Pbaudoliver7 --errors --settings /home/r/settings.xml -Dstyle.color=never
